name: Test package

on:
  # Manual trigger
  workflow_dispatch:

  # Triggered by pull-request-conditionals.yaml
  workflow_call:

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    name: Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Environment setup
        uses: ./.github/actions/setup

      - name: Create test bundle
        run: uds run create-test-bundle

      - name: Setup cluster
        run: uds run setup-cluster
      
      - name: Deploy test bundle
        run: uds run deploy-test-bundle

      - name: Test package
        run: uds run test-packages

      - name: Cleanup
        if: always()
        run: uds run cleanup

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
